---
- hosts: ansible.ebs.local
  gather_facts: true
  become: yes
  become_method: sudo

  vars:
    lvm_groups:
      - vgname: data
        disks:
          - /dev/sdb
        create: true
        lvnames:
          - lvname: dockerfs
            size: 30g
            create: true
            filesystem: xfs
            mount: true
            mntp: /var/lib/docker
          - lvname: dockervolume
            size: 4g
            create: true
            filesystem: xfs
            mount: true
            mntp: /var/lib/docker/volumes
          - lvname: dockermeta
            size: 4g
            create: true
            filesystem: xfs
            mount: true
            mntp: /var/lib/docker/containers
    manage_lvm: true
    pri_domain_name: 'ansible.ebs.local'

  roles:
    - mrlesmithjr.manage-lvm
