---
- name: Configure User Access
  hosts: ansible

  roles:
    - name: sansible.users_and_groups
      sansible_users_and_groups_users:
        - name: docker
          groups:
            - docker
